name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }} building the extension
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: cd schema/
        - run: cd ..
        - run: yarn --frozen-lockfile
        - run: npm install --global vsce
        - name: "Patching the existing extension in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' }}
          run: vsce publish --pre-release -p ${{ secrets.VSCE_TOKEN }}
        - name: "Publishing in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' }}
          run: vsce publish patch --pre-release -p ${{ secrets.VSCE_TOKEN }}


