name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      patch:
        description: 'Patch the existing extension in VS Code Marketplace'
        type: boolean
        required: true
        default: false
      preRelease:
        description: 'Pre release the existing extension in VS Code Marketplace'
        type: boolean
        required: true
        default: false
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }} building the extension
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: cd schema/
        - run: cd ..
        - run: yarn --frozen-lockfile
        - run: npm install --global vsce
        - name: "Patch the pre released extension in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' }}
          run: vsce publish patch --pre-release -p ${{ secrets.VSCE_TOKEN }}
        - name: "Pre release in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'false' }}
          run: vsce publish --pre-release -p ${{ secrets.VSCE_TOKEN }}
        - name: "Release the extension in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' && github.event.inputs.preRelease == 'false' }}
          run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        - name: "Patch the released version in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' && github.event.inputs.preRelease == 'false' }}
          run: vsce publish patch -p ${{ secrets.VSCE_TOKEN }}


